module.exports = {
  "1C Enterprise": require("../data/1c-enterprise"),
  "ABAP": require("../data/abap"),
  "ABNF": require("../data/abnf"),
  "AGS Script": require("../data/ags-script"),
  "AMPL": require("../data/ampl"),
  "ANTLR": require("../data/antlr"),
  "API Blueprint": require("../data/api-blueprint"),
  "APL": require("../data/apl"),
  "ASN.1": require("../data/asn.1"),
  "ASP": require("../data/asp"),
  "ATS": require("../data/ats"),
  "ActionScript": require("../data/actionscript"),
  "Ada": require("../data/ada"),
  "Adobe Font Metrics": require("../data/adobe-font-metrics"),
  "Agda": require("../data/agda"),
  "Alloy": require("../data/alloy"),
  "Alpine Abuild": require("../data/alpine-abuild"),
  "AngelScript": require("../data/angelscript"),
  "Ant Build System": require("../data/ant-build-system"),
  "ApacheConf": require("../data/apacheconf"),
  "Apex": require("../data/apex"),
  "Apollo Guidance Computer": require("../data/apollo-guidance-computer"),
  "AppleScript": require("../data/applescript"),
  "Arc": require("../data/arc"),
  "AsciiDoc": require("../data/asciidoc"),
  "AspectJ": require("../data/aspectj"),
  "Assembly": require("../data/assembly"),
  "Augeas": require("../data/augeas"),
  "AutoHotkey": require("../data/autohotkey"),
  "AutoIt": require("../data/autoit"),
  "Awk": require("../data/awk"),
  "Ballerina": require("../data/ballerina"),
  "Batchfile": require("../data/batchfile"),
  "Befunge": require("../data/befunge"),
  "Bison": require("../data/bison"),
  "BitBake": require("../data/bitbake"),
  "Blade": require("../data/blade"),
  "BlitzBasic": require("../data/blitzbasic"),
  "BlitzMax": require("../data/blitzmax"),
  "Bluespec": require("../data/bluespec"),
  "Boo": require("../data/boo"),
  "Brainfuck": require("../data/brainfuck"),
  "Brightscript": require("../data/brightscript"),
  "Bro": require("../data/bro"),
  "C": require("../data/c"),
  "C#": require("../data/c#"),
  "C++": require("../data/c++"),
  "C-ObjDump": require("../data/c-objdump"),
  "C2hs Haskell": require("../data/c2hs-haskell"),
  "CLIPS": require("../data/clips"),
  "CMake": require("../data/cmake"),
  "COBOL": require("../data/cobol"),
  "COLLADA": require("../data/collada"),
  "CSON": require("../data/cson"),
  "CSS": require("../data/css"),
  "CSV": require("../data/csv"),
  "CWeb": require("../data/cweb"),
  "Cap'n Proto": require("../data/cap'n-proto"),
  "CartoCSS": require("../data/cartocss"),
  "Ceylon": require("../data/ceylon"),
  "Chapel": require("../data/chapel"),
  "Charity": require("../data/charity"),
  "ChucK": require("../data/chuck"),
  "Cirru": require("../data/cirru"),
  "Clarion": require("../data/clarion"),
  "Clean": require("../data/clean"),
  "Click": require("../data/click"),
  "Clojure": require("../data/clojure"),
  "Closure Templates": require("../data/closure-templates"),
  "Cloud Firestore Security Rules": require("../data/cloud-firestore-security-rules"),
  "CoNLL-U": require("../data/conll-u"),
  "CoffeeScript": require("../data/coffeescript"),
  "ColdFusion": require("../data/coldfusion"),
  "ColdFusion CFC": require("../data/coldfusion-cfc"),
  "Common Lisp": require("../data/common-lisp"),
  "Common Workflow Language": require("../data/common-workflow-language"),
  "Component Pascal": require("../data/component-pascal"),
  "Cool": require("../data/cool"),
  "Coq": require("../data/coq"),
  "Cpp-ObjDump": require("../data/cpp-objdump"),
  "Creole": require("../data/creole"),
  "Crystal": require("../data/crystal"),
  "Csound": require("../data/csound"),
  "Csound Document": require("../data/csound-document"),
  "Csound Score": require("../data/csound-score"),
  "Cuda": require("../data/cuda"),
  "Cycript": require("../data/cycript"),
  "Cython": require("../data/cython"),
  "D": require("../data/d"),
  "D-ObjDump": require("../data/d-objdump"),
  "DIGITAL Command Language": require("../data/digital-command-language"),
  "DM": require("../data/dm"),
  "DNS Zone": require("../data/dns-zone"),
  "DTrace": require("../data/dtrace"),
  "Darcs Patch": require("../data/darcs-patch"),
  "Dart": require("../data/dart"),
  "DataWeave": require("../data/dataweave"),
  "Diff": require("../data/diff"),
  "Dockerfile": require("../data/dockerfile"),
  "Dogescript": require("../data/dogescript"),
  "Dylan": require("../data/dylan"),
  "E": require("../data/e"),
  "EBNF": require("../data/ebnf"),
  "ECL": require("../data/ecl"),
  "ECLiPSe": require("../data/eclipse"),
  "EJS": require("../data/ejs"),
  "EQ": require("../data/eq"),
  "Eagle": require("../data/eagle"),
  "Easybuild": require("../data/easybuild"),
  "Ecere Projects": require("../data/ecere-projects"),
  "Edje Data Collection": require("../data/edje-data-collection"),
  "Eiffel": require("../data/eiffel"),
  "Elixir": require("../data/elixir"),
  "Elm": require("../data/elm"),
  "Emacs Lisp": require("../data/emacs-lisp"),
  "EmberScript": require("../data/emberscript"),
  "Erlang": require("../data/erlang"),
  "F#": require("../data/f#"),
  "FLUX": require("../data/flux"),
  "Factor": require("../data/factor"),
  "Fancy": require("../data/fancy"),
  "Fantom": require("../data/fantom"),
  "Filebench WML": require("../data/filebench-wml"),
  "Filterscript": require("../data/filterscript"),
  "Formatted": require("../data/formatted"),
  "Forth": require("../data/forth"),
  "Fortran": require("../data/fortran"),
  "FreeMarker": require("../data/freemarker"),
  "Frege": require("../data/frege"),
  "G-code": require("../data/g-code"),
  "GAMS": require("../data/gams"),
  "GAP": require("../data/gap"),
  "GCC Machine Description": require("../data/gcc-machine-description"),
  "GDB": require("../data/gdb"),
  "GDScript": require("../data/gdscript"),
  "GLSL": require("../data/glsl"),
  "GN": require("../data/gn"),
  "Game Maker Language": require("../data/game-maker-language"),
  "Genie": require("../data/genie"),
  "Genshi": require("../data/genshi"),
  "Gentoo Ebuild": require("../data/gentoo-ebuild"),
  "Gentoo Eclass": require("../data/gentoo-eclass"),
  "Gerber Image": require("../data/gerber-image"),
  "Gettext Catalog": require("../data/gettext-catalog"),
  "Gherkin": require("../data/gherkin"),
  "Glyph": require("../data/glyph"),
  "Gnuplot": require("../data/gnuplot"),
  "Go": require("../data/go"),
  "Golo": require("../data/golo"),
  "Gosu": require("../data/gosu"),
  "Grace": require("../data/grace"),
  "Gradle": require("../data/gradle"),
  "Grammatical Framework": require("../data/grammatical-framework"),
  "Graph Modeling Language": require("../data/graph-modeling-language"),
  "GraphQL": require("../data/graphql"),
  "Graphviz (DOT)": require("../data/graphviz-(dot)"),
  "Groovy": require("../data/groovy"),
  "Groovy Server Pages": require("../data/groovy-server-pages"),
  "HCL": require("../data/hcl"),
  "HLSL": require("../data/hlsl"),
  "HTML": require("../data/html"),
  "HTML+Django": require("../data/html+django"),
  "HTML+ECR": require("../data/html+ecr"),
  "HTML+EEX": require("../data/html+eex"),
  "HTML+ERB": require("../data/html+erb"),
  "HTML+PHP": require("../data/html+php"),
  "HTTP": require("../data/http"),
  "HXML": require("../data/hxml"),
  "Hack": require("../data/hack"),
  "Haml": require("../data/haml"),
  "Handlebars": require("../data/handlebars"),
  "Harbour": require("../data/harbour"),
  "Haskell": require("../data/haskell"),
  "Haxe": require("../data/haxe"),
  "HiveQL": require("../data/hiveql"),
  "Hy": require("../data/hy"),
  "HyPhy": require("../data/hyphy"),
  "IDL": require("../data/idl"),
  "IGOR Pro": require("../data/igor-pro"),
  "INI": require("../data/ini"),
  "IRC log": require("../data/irc-log"),
  "Idris": require("../data/idris"),
  "Inform 7": require("../data/inform-7"),
  "Inno Setup": require("../data/inno-setup"),
  "Io": require("../data/io"),
  "Ioke": require("../data/ioke"),
  "Isabelle": require("../data/isabelle"),
  "Isabelle ROOT": require("../data/isabelle-root"),
  "J": require("../data/j"),
  "JFlex": require("../data/jflex"),
  "JSON": require("../data/json"),
  "JSON with Comments": require("../data/json-with-comments"),
  "JSON5": require("../data/json5"),
  "JSONLD": require("../data/jsonld"),
  "JSONiq": require("../data/jsoniq"),
  "JSX": require("../data/jsx"),
  "Jasmin": require("../data/jasmin"),
  "Java": require("../data/java"),
  "Java Server Pages": require("../data/java-server-pages"),
  "JavaScript": require("../data/javascript"),
  "Jison": require("../data/jison"),
  "Jison Lex": require("../data/jison-lex"),
  "Jolie": require("../data/jolie"),
  "Julia": require("../data/julia"),
  "Jupyter Notebook": require("../data/jupyter-notebook"),
  "KRL": require("../data/krl"),
  "KiCad Layout": require("../data/kicad-layout"),
  "KiCad Legacy Layout": require("../data/kicad-legacy-layout"),
  "KiCad Schematic": require("../data/kicad-schematic"),
  "Kit": require("../data/kit"),
  "Kotlin": require("../data/kotlin"),
  "LFE": require("../data/lfe"),
  "LLVM": require("../data/llvm"),
  "LOLCODE": require("../data/lolcode"),
  "LSL": require("../data/lsl"),
  "LabVIEW": require("../data/labview"),
  "Lasso": require("../data/lasso"),
  "Latte": require("../data/latte"),
  "Lean": require("../data/lean"),
  "Less": require("../data/less"),
  "Lex": require("../data/lex"),
  "LilyPond": require("../data/lilypond"),
  "Limbo": require("../data/limbo"),
  "Linker Script": require("../data/linker-script"),
  "Linux Kernel Module": require("../data/linux-kernel-module"),
  "Liquid": require("../data/liquid"),
  "Literate Agda": require("../data/literate-agda"),
  "Literate CoffeeScript": require("../data/literate-coffeescript"),
  "Literate Haskell": require("../data/literate-haskell"),
  "LiveScript": require("../data/livescript"),
  "Logos": require("../data/logos"),
  "Logtalk": require("../data/logtalk"),
  "LookML": require("../data/lookml"),
  "LoomScript": require("../data/loomscript"),
  "Lua": require("../data/lua"),
  "M": require("../data/m"),
  "M4": require("../data/m4"),
  "M4Sugar": require("../data/m4sugar"),
  "MAXScript": require("../data/maxscript"),
  "MQL4": require("../data/mql4"),
  "MQL5": require("../data/mql5"),
  "MTML": require("../data/mtml"),
  "MUF": require("../data/muf"),
  "Makefile": require("../data/makefile"),
  "Mako": require("../data/mako"),
  "Markdown": require("../data/markdown"),
  "Marko": require("../data/marko"),
  "Mask": require("../data/mask"),
  "Mathematica": require("../data/mathematica"),
  "Matlab": require("../data/matlab"),
  "Maven POM": require("../data/maven-pom"),
  "Max": require("../data/max"),
  "MediaWiki": require("../data/mediawiki"),
  "Mercury": require("../data/mercury"),
  "Meson": require("../data/meson"),
  "Metal": require("../data/metal"),
  "MiniD": require("../data/minid"),
  "Mirah": require("../data/mirah"),
  "Modelica": require("../data/modelica"),
  "Modula-2": require("../data/modula-2"),
  "Module Management System": require("../data/module-management-system"),
  "Monkey": require("../data/monkey"),
  "Moocode": require("../data/moocode"),
  "MoonScript": require("../data/moonscript"),
  "Myghty": require("../data/myghty"),
  "NCL": require("../data/ncl"),
  "NL": require("../data/nl"),
  "NSIS": require("../data/nsis"),
  "Nearley": require("../data/nearley"),
  "Nemerle": require("../data/nemerle"),
  "NetLinx": require("../data/netlinx"),
  "NetLinx+ERB": require("../data/netlinx+erb"),
  "NetLogo": require("../data/netlogo"),
  "NewLisp": require("../data/newlisp"),
  "Nextflow": require("../data/nextflow"),
  "Nginx": require("../data/nginx"),
  "Nim": require("../data/nim"),
  "Ninja": require("../data/ninja"),
  "Nit": require("../data/nit"),
  "Nix": require("../data/nix"),
  "Nu": require("../data/nu"),
  "NumPy": require("../data/numpy"),
  "OCaml": require("../data/ocaml"),
  "ObjDump": require("../data/objdump"),
  "Objective-C": require("../data/objective-c"),
  "Objective-C++": require("../data/objective-c++"),
  "Objective-J": require("../data/objective-j"),
  "Omgrofl": require("../data/omgrofl"),
  "Opa": require("../data/opa"),
  "Opal": require("../data/opal"),
  "OpenCL": require("../data/opencl"),
  "OpenEdge ABL": require("../data/openedge-abl"),
  "OpenRC runscript": require("../data/openrc-runscript"),
  "OpenSCAD": require("../data/openscad"),
  "OpenType Feature File": require("../data/opentype-feature-file"),
  "Org": require("../data/org"),
  "Ox": require("../data/ox"),
  "Oxygene": require("../data/oxygene"),
  "Oz": require("../data/oz"),
  "P4": require("../data/p4"),
  "PAWN": require("../data/pawn"),
  "PHP": require("../data/php"),
  "PLSQL": require("../data/plsql"),
  "PLpgSQL": require("../data/plpgsql"),
  "POV-Ray SDL": require("../data/pov-ray-sdl"),
  "Pan": require("../data/pan"),
  "Papyrus": require("../data/papyrus"),
  "Parrot": require("../data/parrot"),
  "Parrot Assembly": require("../data/parrot-assembly"),
  "Parrot Internal Representation": require("../data/parrot-internal-representation"),
  "Pascal": require("../data/pascal"),
  "Pep8": require("../data/pep8"),
  "Perl": require("../data/perl"),
  "Perl 6": require("../data/perl-6"),
  "Pic": require("../data/pic"),
  "Pickle": require("../data/pickle"),
  "PicoLisp": require("../data/picolisp"),
  "PigLatin": require("../data/piglatin"),
  "Pike": require("../data/pike"),
  "Pod": require("../data/pod"),
  "PogoScript": require("../data/pogoscript"),
  "Pony": require("../data/pony"),
  "PostCSS": require("../data/postcss"),
  "PostScript": require("../data/postscript"),
  "PowerBuilder": require("../data/powerbuilder"),
  "PowerShell": require("../data/powershell"),
  "Processing": require("../data/processing"),
  "Prolog": require("../data/prolog"),
  "Propeller Spin": require("../data/propeller-spin"),
  "Protocol Buffer": require("../data/protocol-buffer"),
  "Public Key": require("../data/public-key"),
  "Pug": require("../data/pug"),
  "Puppet": require("../data/puppet"),
  "Pure Data": require("../data/pure-data"),
  "PureBasic": require("../data/purebasic"),
  "PureScript": require("../data/purescript"),
  "Python": require("../data/python"),
  "Python console": require("../data/python-console"),
  "Python traceback": require("../data/python-traceback"),
  "QML": require("../data/qml"),
  "QMake": require("../data/qmake"),
  "R": require("../data/r"),
  "RAML": require("../data/raml"),
  "RDoc": require("../data/rdoc"),
  "REALbasic": require("../data/realbasic"),
  "REXX": require("../data/rexx"),
  "RHTML": require("../data/rhtml"),
  "RMarkdown": require("../data/rmarkdown"),
  "RPC": require("../data/rpc"),
  "RPM Spec": require("../data/rpm-spec"),
  "RUNOFF": require("../data/runoff"),
  "Racket": require("../data/racket"),
  "Ragel": require("../data/ragel"),
  "Rascal": require("../data/rascal"),
  "Raw token data": require("../data/raw-token-data"),
  "Reason": require("../data/reason"),
  "Rebol": require("../data/rebol"),
  "Red": require("../data/red"),
  "Redcode": require("../data/redcode"),
  "Regular Expression": require("../data/regular-expression"),
  "Ren'Py": require("../data/ren'py"),
  "RenderScript": require("../data/renderscript"),
  "Ring": require("../data/ring"),
  "RobotFramework": require("../data/robotframework"),
  "Roff": require("../data/roff"),
  "Rouge": require("../data/rouge"),
  "Ruby": require("../data/ruby"),
  "Rust": require("../data/rust"),
  "SAS": require("../data/sas"),
  "SCSS": require("../data/scss"),
  "SMT": require("../data/smt"),
  "SPARQL": require("../data/sparql"),
  "SQF": require("../data/sqf"),
  "SQL": require("../data/sql"),
  "SQLPL": require("../data/sqlpl"),
  "SRecode Template": require("../data/srecode-template"),
  "STON": require("../data/ston"),
  "SVG": require("../data/svg"),
  "Sage": require("../data/sage"),
  "SaltStack": require("../data/saltstack"),
  "Sass": require("../data/sass"),
  "Scala": require("../data/scala"),
  "Scaml": require("../data/scaml"),
  "Scheme": require("../data/scheme"),
  "Scilab": require("../data/scilab"),
  "Self": require("../data/self"),
  "ShaderLab": require("../data/shaderlab"),
  "Shell": require("../data/shell"),
  "ShellSession": require("../data/shellsession"),
  "Shen": require("../data/shen"),
  "Slash": require("../data/slash"),
  "Slim": require("../data/slim"),
  "Smali": require("../data/smali"),
  "Smalltalk": require("../data/smalltalk"),
  "Smarty": require("../data/smarty"),
  "Solidity": require("../data/solidity"),
  "SourcePawn": require("../data/sourcepawn"),
  "Spline Font Database": require("../data/spline-font-database"),
  "Squirrel": require("../data/squirrel"),
  "Stan": require("../data/stan"),
  "Standard ML": require("../data/standard-ml"),
  "Stata": require("../data/stata"),
  "Stylus": require("../data/stylus"),
  "SubRip Text": require("../data/subrip-text"),
  "SugarSS": require("../data/sugarss"),
  "SuperCollider": require("../data/supercollider"),
  "Swift": require("../data/swift"),
  "SystemVerilog": require("../data/systemverilog"),
  "TI Program": require("../data/ti-program"),
  "TLA": require("../data/tla"),
  "TOML": require("../data/toml"),
  "TXL": require("../data/txl"),
  "Tcl": require("../data/tcl"),
  "Tcsh": require("../data/tcsh"),
  "TeX": require("../data/tex"),
  "Tea": require("../data/tea"),
  "Terra": require("../data/terra"),
  "Text": require("../data/text"),
  "Textile": require("../data/textile"),
  "Thrift": require("../data/thrift"),
  "Turing": require("../data/turing"),
  "Turtle": require("../data/turtle"),
  "Twig": require("../data/twig"),
  "Type Language": require("../data/type-language"),
  "TypeScript": require("../data/typescript"),
  "Unified Parallel C": require("../data/unified-parallel-c"),
  "Unity3D Asset": require("../data/unity3d-asset"),
  "Unix Assembly": require("../data/unix-assembly"),
  "Uno": require("../data/uno"),
  "UnrealScript": require("../data/unrealscript"),
  "UrWeb": require("../data/urweb"),
  "VCL": require("../data/vcl"),
  "VHDL": require("../data/vhdl"),
  "Vala": require("../data/vala"),
  "Verilog": require("../data/verilog"),
  "Vim script": require("../data/vim-script"),
  "Visual Basic": require("../data/visual-basic"),
  "Volt": require("../data/volt"),
  "Vue": require("../data/vue"),
  "Wavefront Material": require("../data/wavefront-material"),
  "Wavefront Object": require("../data/wavefront-object"),
  "Web Ontology Language": require("../data/web-ontology-language"),
  "WebAssembly": require("../data/webassembly"),
  "WebIDL": require("../data/webidl"),
  "World of Warcraft Addon Data": require("../data/world-of-warcraft-addon-data"),
  "X BitMap": require("../data/x-bitmap"),
  "X PixMap": require("../data/x-pixmap"),
  "X10": require("../data/x10"),
  "XC": require("../data/xc"),
  "XCompose": require("../data/xcompose"),
  "XML": require("../data/xml"),
  "XPages": require("../data/xpages"),
  "XProc": require("../data/xproc"),
  "XQuery": require("../data/xquery"),
  "XS": require("../data/xs"),
  "XSLT": require("../data/xslt"),
  "Xojo": require("../data/xojo"),
  "Xtend": require("../data/xtend"),
  "YAML": require("../data/yaml"),
  "YANG": require("../data/yang"),
  "YARA": require("../data/yara"),
  "Yacc": require("../data/yacc"),
  "Zephir": require("../data/zephir"),
  "Zimpl": require("../data/zimpl"),
  "desktop": require("../data/desktop"),
  "eC": require("../data/ec"),
  "edn": require("../data/edn"),
  "fish": require("../data/fish"),
  "mupad": require("../data/mupad"),
  "nesC": require("../data/nesc"),
  "ooc": require("../data/ooc"),
  "q": require("../data/q"),
  "reStructuredText": require("../data/restructuredtext"),
  "sed": require("../data/sed"),
  "wdl": require("../data/wdl"),
  "wisp": require("../data/wisp"),
  "xBase": require("../data/xbase")
};
