type LanguageName =
  | "1C Enterprise"
  | "ABAP"
  | "ABNF"
  | "AGS Script"
  | "AMPL"
  | "ANTLR"
  | "API Blueprint"
  | "APL"
  | "ASN.1"
  | "ASP"
  | "ATS"
  | "ActionScript"
  | "Ada"
  | "Adobe Font Metrics"
  | "Agda"
  | "Alloy"
  | "Alpine Abuild"
  | "AngelScript"
  | "Ant Build System"
  | "ApacheConf"
  | "Apex"
  | "Apollo Guidance Computer"
  | "AppleScript"
  | "Arc"
  | "AsciiDoc"
  | "AspectJ"
  | "Assembly"
  | "Augeas"
  | "AutoHotkey"
  | "AutoIt"
  | "Awk"
  | "Ballerina"
  | "Batchfile"
  | "Befunge"
  | "Bison"
  | "BitBake"
  | "Blade"
  | "BlitzBasic"
  | "BlitzMax"
  | "Bluespec"
  | "Boo"
  | "Brainfuck"
  | "Brightscript"
  | "Bro"
  | "C"
  | "C#"
  | "C++"
  | "C-ObjDump"
  | "C2hs Haskell"
  | "CLIPS"
  | "CMake"
  | "COBOL"
  | "COLLADA"
  | "CSON"
  | "CSS"
  | "CSV"
  | "CWeb"
  | "Cap'n Proto"
  | "CartoCSS"
  | "Ceylon"
  | "Chapel"
  | "Charity"
  | "ChucK"
  | "Cirru"
  | "Clarion"
  | "Clean"
  | "Click"
  | "Clojure"
  | "Closure Templates"
  | "Cloud Firestore Security Rules"
  | "CoNLL-U"
  | "CoffeeScript"
  | "ColdFusion"
  | "ColdFusion CFC"
  | "Common Lisp"
  | "Common Workflow Language"
  | "Component Pascal"
  | "Cool"
  | "Coq"
  | "Cpp-ObjDump"
  | "Creole"
  | "Crystal"
  | "Csound"
  | "Csound Document"
  | "Csound Score"
  | "Cuda"
  | "Cycript"
  | "Cython"
  | "D"
  | "D-ObjDump"
  | "DIGITAL Command Language"
  | "DM"
  | "DNS Zone"
  | "DTrace"
  | "Darcs Patch"
  | "Dart"
  | "DataWeave"
  | "Diff"
  | "Dockerfile"
  | "Dogescript"
  | "Dylan"
  | "E"
  | "EBNF"
  | "ECL"
  | "ECLiPSe"
  | "EJS"
  | "EQ"
  | "Eagle"
  | "Easybuild"
  | "Ecere Projects"
  | "Edje Data Collection"
  | "Eiffel"
  | "Elixir"
  | "Elm"
  | "Emacs Lisp"
  | "EmberScript"
  | "Erlang"
  | "F#"
  | "FLUX"
  | "Factor"
  | "Fancy"
  | "Fantom"
  | "Filebench WML"
  | "Filterscript"
  | "Formatted"
  | "Forth"
  | "Fortran"
  | "FreeMarker"
  | "Frege"
  | "G-code"
  | "GAMS"
  | "GAP"
  | "GCC Machine Description"
  | "GDB"
  | "GDScript"
  | "GLSL"
  | "GN"
  | "Game Maker Language"
  | "Genie"
  | "Genshi"
  | "Gentoo Ebuild"
  | "Gentoo Eclass"
  | "Gerber Image"
  | "Gettext Catalog"
  | "Gherkin"
  | "Glyph"
  | "Gnuplot"
  | "Go"
  | "Golo"
  | "Gosu"
  | "Grace"
  | "Gradle"
  | "Grammatical Framework"
  | "Graph Modeling Language"
  | "GraphQL"
  | "Graphviz (DOT)"
  | "Groovy"
  | "Groovy Server Pages"
  | "HCL"
  | "HLSL"
  | "HTML"
  | "HTML+Django"
  | "HTML+ECR"
  | "HTML+EEX"
  | "HTML+ERB"
  | "HTML+PHP"
  | "HTTP"
  | "HXML"
  | "Hack"
  | "Haml"
  | "Handlebars"
  | "Harbour"
  | "Haskell"
  | "Haxe"
  | "HiveQL"
  | "Hy"
  | "HyPhy"
  | "IDL"
  | "IGOR Pro"
  | "INI"
  | "IRC log"
  | "Idris"
  | "Inform 7"
  | "Inno Setup"
  | "Io"
  | "Ioke"
  | "Isabelle"
  | "Isabelle ROOT"
  | "J"
  | "JFlex"
  | "JSON"
  | "JSON with Comments"
  | "JSON5"
  | "JSONLD"
  | "JSONiq"
  | "JSX"
  | "Jasmin"
  | "Java"
  | "Java Server Pages"
  | "JavaScript"
  | "Jison"
  | "Jison Lex"
  | "Jolie"
  | "Julia"
  | "Jupyter Notebook"
  | "KRL"
  | "KiCad Layout"
  | "KiCad Legacy Layout"
  | "KiCad Schematic"
  | "Kit"
  | "Kotlin"
  | "LFE"
  | "LLVM"
  | "LOLCODE"
  | "LSL"
  | "LabVIEW"
  | "Lasso"
  | "Latte"
  | "Lean"
  | "Less"
  | "Lex"
  | "LilyPond"
  | "Limbo"
  | "Linker Script"
  | "Linux Kernel Module"
  | "Liquid"
  | "Literate Agda"
  | "Literate CoffeeScript"
  | "Literate Haskell"
  | "LiveScript"
  | "Logos"
  | "Logtalk"
  | "LookML"
  | "LoomScript"
  | "Lua"
  | "M"
  | "M4"
  | "M4Sugar"
  | "MAXScript"
  | "MQL4"
  | "MQL5"
  | "MTML"
  | "MUF"
  | "Makefile"
  | "Mako"
  | "Markdown"
  | "Marko"
  | "Mask"
  | "Mathematica"
  | "Matlab"
  | "Maven POM"
  | "Max"
  | "MediaWiki"
  | "Mercury"
  | "Meson"
  | "Metal"
  | "MiniD"
  | "Mirah"
  | "Modelica"
  | "Modula-2"
  | "Module Management System"
  | "Monkey"
  | "Moocode"
  | "MoonScript"
  | "Myghty"
  | "NCL"
  | "NL"
  | "NSIS"
  | "Nearley"
  | "Nemerle"
  | "NetLinx"
  | "NetLinx+ERB"
  | "NetLogo"
  | "NewLisp"
  | "Nextflow"
  | "Nginx"
  | "Nim"
  | "Ninja"
  | "Nit"
  | "Nix"
  | "Nu"
  | "NumPy"
  | "OCaml"
  | "ObjDump"
  | "Objective-C"
  | "Objective-C++"
  | "Objective-J"
  | "Omgrofl"
  | "Opa"
  | "Opal"
  | "OpenCL"
  | "OpenEdge ABL"
  | "OpenRC runscript"
  | "OpenSCAD"
  | "OpenType Feature File"
  | "Org"
  | "Ox"
  | "Oxygene"
  | "Oz"
  | "P4"
  | "PAWN"
  | "PHP"
  | "PLSQL"
  | "PLpgSQL"
  | "POV-Ray SDL"
  | "Pan"
  | "Papyrus"
  | "Parrot"
  | "Parrot Assembly"
  | "Parrot Internal Representation"
  | "Pascal"
  | "Pep8"
  | "Perl"
  | "Perl 6"
  | "Pic"
  | "Pickle"
  | "PicoLisp"
  | "PigLatin"
  | "Pike"
  | "Pod"
  | "PogoScript"
  | "Pony"
  | "PostCSS"
  | "PostScript"
  | "PowerBuilder"
  | "PowerShell"
  | "Processing"
  | "Prolog"
  | "Propeller Spin"
  | "Protocol Buffer"
  | "Public Key"
  | "Pug"
  | "Puppet"
  | "Pure Data"
  | "PureBasic"
  | "PureScript"
  | "Python"
  | "Python console"
  | "Python traceback"
  | "QML"
  | "QMake"
  | "R"
  | "RAML"
  | "RDoc"
  | "REALbasic"
  | "REXX"
  | "RHTML"
  | "RMarkdown"
  | "RPC"
  | "RPM Spec"
  | "RUNOFF"
  | "Racket"
  | "Ragel"
  | "Rascal"
  | "Raw token data"
  | "Reason"
  | "Rebol"
  | "Red"
  | "Redcode"
  | "Regular Expression"
  | "Ren'Py"
  | "RenderScript"
  | "Ring"
  | "RobotFramework"
  | "Roff"
  | "Rouge"
  | "Ruby"
  | "Rust"
  | "SAS"
  | "SCSS"
  | "SMT"
  | "SPARQL"
  | "SQF"
  | "SQL"
  | "SQLPL"
  | "SRecode Template"
  | "STON"
  | "SVG"
  | "Sage"
  | "SaltStack"
  | "Sass"
  | "Scala"
  | "Scaml"
  | "Scheme"
  | "Scilab"
  | "Self"
  | "ShaderLab"
  | "Shell"
  | "ShellSession"
  | "Shen"
  | "Slash"
  | "Slim"
  | "Smali"
  | "Smalltalk"
  | "Smarty"
  | "Solidity"
  | "SourcePawn"
  | "Spline Font Database"
  | "Squirrel"
  | "Stan"
  | "Standard ML"
  | "Stata"
  | "Stylus"
  | "SubRip Text"
  | "SugarSS"
  | "SuperCollider"
  | "Swift"
  | "SystemVerilog"
  | "TI Program"
  | "TLA"
  | "TOML"
  | "TXL"
  | "Tcl"
  | "Tcsh"
  | "TeX"
  | "Tea"
  | "Terra"
  | "Text"
  | "Textile"
  | "Thrift"
  | "Turing"
  | "Turtle"
  | "Twig"
  | "Type Language"
  | "TypeScript"
  | "Unified Parallel C"
  | "Unity3D Asset"
  | "Unix Assembly"
  | "Uno"
  | "UnrealScript"
  | "UrWeb"
  | "VCL"
  | "VHDL"
  | "Vala"
  | "Verilog"
  | "Vim script"
  | "Visual Basic"
  | "Volt"
  | "Vue"
  | "Wavefront Material"
  | "Wavefront Object"
  | "Web Ontology Language"
  | "WebAssembly"
  | "WebIDL"
  | "World of Warcraft Addon Data"
  | "X BitMap"
  | "X PixMap"
  | "X10"
  | "XC"
  | "XCompose"
  | "XML"
  | "XPages"
  | "XProc"
  | "XQuery"
  | "XS"
  | "XSLT"
  | "Xojo"
  | "Xtend"
  | "YAML"
  | "YANG"
  | "YARA"
  | "Yacc"
  | "Zephir"
  | "Zimpl"
  | "desktop"
  | "eC"
  | "edn"
  | "fish"
  | "mupad"
  | "nesC"
  | "ooc"
  | "q"
  | "reStructuredText"
  | "sed"
  | "wdl"
  | "wisp"
  | "xBase";

declare const LinguistLanguages: Record<LanguageName, LinguistLanguages.Language>;

declare namespace LinguistLanguages {
  interface Language {
    name: string;
    type: string;
    color?: string;
    extensions?: string[];
    tmScope?: string;
    aceMode: string;
    languageId: number;
    aliases?: string[];
    codemirrorMode?: string;
    codemirrorMimeType?: string;
    interpreters?: string[];
    group?: string;
    filenames?: string[];
    wrap?: boolean;
    searchable?: boolean;
  }
}

export = LinguistLanguages;
